default_ethereum_client_images:
  lighthouse: ethpandaops/lighthouse:ethdreamer-unstable-instrument-beacon-api
  geth: ethpandaops/geth:master

lighthouse_container_command_extra_args:
  - --testnet-dir=/network-config
  - --boot-nodes={{ ethereum_cl_bootnodes | join(',') }}
  - --disable-get-blobs
  - --telemetry-collector-url=http://grpc-snoop:1337
  - --telemetry-service-name={{ ethereum_network_name }}-{{ inventory_hostname }}
  - --debug-level=debug