localhost

[all:vars]
ethereum_network_name=fusaka-msf-1

[bootnode]
bootnode-1 ansible_host=174.138.43.175 ipv6=2604:a880:400:d1:0:3:4478:a001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True 

[grandine_geth_super]
grandine-geth-super-1 ansible_host=104.248.228.76 ipv6=2604:a880:400:d1:0:3:4478:d001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=5000 validator_end=6000

[lighthouse_geth_super]
lighthouse-geth-super-1 ansible_host=165.22.12.63 ipv6=2604:a880:400:d1:0:3:4478:f001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=1000

[lighthouse_nethermind_super]
lighthouse-nethermind-super-1 ansible_host=161.35.124.69 ipv6=2604:a880:400:d1:0:3:4478:c001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=6000 validator_end=7000

[lighthouse_reth_super]
lighthouse-reth-super-1 ansible_host=165.22.3.133 ipv6=2604:a880:400:d1:0:3:4478:b001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=9000 validator_end=10000

[lodestar_besu_super]
lodestar-besu-super-1 ansible_host=159.65.221.76 ipv6=2604:a880:400:d1:0:3:4479:1001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=10000 validator_end=11000

[lodestar_reth_super]
lodestar-reth-super-1 ansible_host=146.190.215.220 ipv6=2604:a880:400:d1:0:3:4478:e001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=4000 validator_end=5000

[nimbus_erigon_super]
nimbus-erigon-super-1 ansible_host=167.71.28.180 ipv6=2604:a880:400:d1:0:3:4479:1 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=3000 validator_end=4000

[nimbus_reth_super]
nimbus-reth-super-1 ansible_host=204.48.24.239 ipv6=2604:a880:400:d1:0:3:4478:6001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=11000 validator_end=12000

[prysm_besu_super]
prysm-besu-super-1 ansible_host=157.230.233.61 ipv6=2604:a880:400:d1:0:3:4478:8001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=7000 validator_end=8000

[prysm_nethermind_super]
prysm-nethermind-super-1 ansible_host=134.209.223.20 ipv6=2604:a880:400:d1:0:3:4478:5001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=2000

[teku_besu_super]
teku-besu-super-1 ansible_host=167.71.22.255 ipv6=2604:a880:400:d1:0:3:4478:7001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=2000 validator_end=3000

[teku_erigon_super]
teku-erigon-super-1 ansible_host=67.205.177.182 ipv6=2604:a880:400:d1:0:3:4478:9001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=8000 validator_end=9000


# Consensus client groups

[lighthouse:children]
lighthouse_geth_super
lighthouse_nethermind_super
lighthouse_reth_super
[lodestar:children]
lodestar_besu_super
lodestar_reth_super
[nimbus:children]
nimbus_erigon_super
nimbus_reth_super
[teku:children]
teku_besu_super
teku_erigon_super
[prysm:children]
prysm_besu_super
prysm_nethermind_super
[grandine:children]
grandine_geth_super

# Execution client groups

[besu:children]
lodestar_besu_super
prysm_besu_super
teku_besu_super
[ethereumjs:children]
[geth:children]
grandine_geth_super
lighthouse_geth_super
[nethermind:children]
lighthouse_nethermind_super
prysm_nethermind_super
[erigon:children]
nimbus_erigon_super
teku_erigon_super
[reth:children]
lighthouse_reth_super
lodestar_reth_super
nimbus_reth_super
[nimbusel:children]

# Global groups

[consensus_node:children]
grandine
lighthouse
lodestar
nimbus
prysm
teku

[execution_node:children]
besu
erigon
geth
nethermind
reth

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
