xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "fusaka-sepsf-0-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "fusaka-sepsf-0"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://0d8703af3992cacfa4eea42a65a0677cdfcb49b6a16f2dc585f90f3e2f968648b03b60ba99838b60329f1b25e1c5960b32c153c85f9f4d0672398f4d821bd3c7@165.22.186.105:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
