default_ethereum_client_images:
  prysm: ethpandaops/prysm-beacon-chain:develop
  prysm_validator: ethpandaops/prysm-validator:develop

  geth: ethpandaops/geth:master-d95ca2e

geth_container_command_extra_args:
  - --http.api=eth,net,web3,debug,admin,txpool
  - --http.vhosts=*
  - --networkid={{ ethereum_network_id }}
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --miner.gaslimit=100000000
  - --vmodule="eth/downloader=5,core=5,catalyst=5"

geth_init_custom_network: true
geth_init_custom_network_genesis_file: "{{ eth_testnet_config_dir }}/genesis.json"
geth_init_custom_network_container_command:
  - --datadir=/data
  - init
  - /genesis.json