# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/checkpointz.yaml.j2

checkpointz:
  fullnameOverride: checkpointz
  replicas: 1

  image:
    repository: ethpandaops/checkpointz
    tag: 0.0.6-fulu
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 64m
      memory: 256Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: checkpoint-sync.fusaka-devnet-5.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

    tls:
    - hosts:
      - checkpoint-sync.fusaka-devnet-5.ethpandaops.io
      secretName: fusaka-devnet-5-checkpoint-sync-tls

  config:
    global:
      listenAddr: ":5555"
      logging: "info" # panic,fatal,warm,info,debug,trace
      metricsAddr: ":9090"

    checkpointz:
      mode: full
      caches:
        blocks:
          max_items: 100
        states:
          max_items: 5
      historical_epoch_count: 20

    beacon:
      upstreams:
        - name: rpc-prysm-geth-001
          address: http://prysm-geth-001:5052
          dataProvider: true
        - name: grandine-besu-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-grandine-besu-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: grandine-erigon-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-grandine-erigon-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: grandine-geth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-grandine-geth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: grandine-nethermind-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-grandine-nethermind-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: grandine-reth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-grandine-reth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lighthouse-besu-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lighthouse-besu-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lighthouse-erigon-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lighthouse-erigon-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lighthouse-geth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lighthouse-geth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lighthouse-nethermind-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lighthouse-nethermind-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lighthouse-reth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lighthouse-reth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lodestar-besu-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lodestar-besu-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lodestar-erigon-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lodestar-erigon-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lodestar-geth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lodestar-geth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lodestar-nethermind-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lodestar-nethermind-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: lodestar-reth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-lodestar-reth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: nimbus-besu-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-nimbus-besu-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: nimbus-erigon-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-nimbus-erigon-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: nimbus-geth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-nimbus-geth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: nimbus-nethermind-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-nimbus-nethermind-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: nimbus-reth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-nimbus-reth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: prysm-besu-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-prysm-besu-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: prysm-erigon-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-prysm-erigon-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: prysm-geth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-prysm-geth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: prysm-nethermind-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-prysm-nethermind-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: prysm-reth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-prysm-reth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: teku-besu-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-teku-besu-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: teku-erigon-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-teku-erigon-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: teku-geth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-teku-geth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: teku-nethermind-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-teku-nethermind-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
        - name: teku-reth-super-1
          address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@bn-teku-reth-super-1.srv.fusaka-devnet-5.ethpandaops.io
          dataProvider: true
