secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:UAbtTHRnXHispR1iQr/5eQMV7JMk5g==,iv:WkDvniP4a1cjpRTQqT0MnJo9UkIp+iwJ3NPSTb8sFsU=,tag:yXavQCYBVJsPHwmm2WbwSg==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:V7U8TluhY0y550IjMfubUgHSFCdxqS109TwWjSGx818J2So5zrTJR0TWzRl1bH4/9MyqCpEtTLHzLlL0j7I4XzgNvrm8qjpeNw3yRa94eyWH5EJT8VI=,iv:Evd5W8ORLtUa3sSl6XeaqY69p0FAmpiFmjXDlP+XbUY=,tag:A34c1/jnfKSFjuDf/2stYA==,type:str]
secret_prometheus_remote_write:
    username: ENC[AES256_GCM,data:cXvFeps2+9h+JAGySH7o,iv:9MCyhKJHtb5BGm7F6Jnl+mSUDjplYid3kCJenN63rq0=,tag:IvLmGPi13zuUGGYhuFYFmw==,type:str]
    password: ENC[AES256_GCM,data:IxuW3G3k1VjgC7VKTgLTFFt2GsNyL/l8w4bwsEKKcExczbze,iv:/fkDq23Aj8PjGMtpem/yd0ont8FcOJxqIpSnNPCts/Y=,tag:azjkoK2xZ7763HN8/6cU/g==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:ldGgCOoW5qVIWwPRGD0QujD7YSTaL1h3jyl7JLRnim3yywXdqi9+ABJ6t4P/wZyNVSp2Y68ObMQ=,iv:A7oFYrwv7Aszp7348IQ/9qv1RWl3oe7PigjygkV43+I=,tag:ma3U6H1kUb8YtNxrxdVORA==,type:str]
    username: ENC[AES256_GCM,data:NY5+HnuzuiX3gM38V3ID,iv:TcF+aW3fhzW8tPMaNM4QHGytRtzxfs/6DveKsX42xIw=,tag:VTPFc9oeeB7USfv4f4O4dg==,type:str]
    password: ENC[AES256_GCM,data:OGZFK/2wsimkIhgjVyDeuIXTd8WVJGgCZ5mHMOV2pDrFhVRg,iv:331+yEvbY65tXnuhd7rNyMMwRKRKT51YB/JBRq5eacA=,tag:w9DDIub9Ql7Gk8GmKCetPQ==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:O7L3,iv:DiOGlqfOfrDlt7X4OGY27OYlkDDEHguv+kg1zRhBek0=,tag:KuOX20lI/iYZOORFraiISw==,type:str]
    password: ENC[AES256_GCM,data:HyMDeoK5s6JDfsJ7j5Gg,iv:yvC4WWOOJvVeegWl0uj2P8yxcfBgNrvYSm5xUB5qux8=,tag:XoZbXpvLtUJPVoEaV3ltsg==,type:str]
secret_ethstats: ENC[AES256_GCM,data:vO/gY2iluciwksE=,iv:WHYxXgQ2LdLGMKxvagmT3UhmQl/dRucpyhYzZxHvLHc=,tag:NX4Lkg6SPPusRx/zHGn00w==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:zRxUC65Kt1b8DM4QPyEJ/u0Uhp2ftMcJVtacbXRrOCUGm+gy0n+VH199hVxvviouJQkbv5FiJYiFjwjJ/yFX5ajPgOqanjRpBfEfwwD2Drtafaw/mWT7pSILHlo7oI18+bGIWjXve5mpUSuAC7jiaufDVROvSa6bcew0Ogbp5pzbFJBFFim3LFjyC1uSRO7JbRoK4cUl1CxnaCUaC/3GKz4l/fIe,iv:EaQilsQbnswzCqkWSK9G/R3wwmMRDwWZDjdZQ1fUZRk=,tag:2kWU1BNG/B82qzmNxmwIjQ==,type:str]
for_sharing_el_cl_mnemonic: ENC[AES256_GCM,data:disXXlEJrJAPidr44qS2NISX+mLtjLKPcOJuB8ws8lcUI1tz2kO5MfYF/3pnJJJn7pq8fLT2gDBkljyejmsOhqSURaRdAyU5mbgNnt6eF+7ZJz0gnuTeBGFzZ4JdywUWcWStefcbdoXeeBxTaaRkLds2gNXY6dtCabR3DTL1BABL3pb39wAE3KkAfxa+NPGkmHA8/V3PQ3LIjA==,iv:AYU9+L/k0d4U9rUmsn7AhN/ENPBZiYhE66TWeeh8jCo=,tag:7/1QSVocgjQk9FC3lajLug==,type:str]
secret_mev_signingkey: ENC[AES256_GCM,data:UVCiQWoe1FWu82UGJf6ed2FeXruOtJMp+NGEOkTQSyVBVOFgZSU6yd6ntwLe0bqChlAzTjTMRXTuk9Ld/7+Rvg==,iv:UqBAaftw7e3cEznwiijNrhGqER2/Qn7hLOfGe4IryYY=,tag:XYM0FhIijik2Bh5QeKwiXQ==,type:str]
secret_mev_flood_private_key: ENC[AES256_GCM,data:LYJDMo2JUMH5TnRJ/DiTpeF+u5oKTRJzpLwNte1QA84e8JNtKlehUDH5XX+rzoyOI3edHm4gwZ5oIeziY1STJA==,iv:1qNfUVqJ9eebRmA4Ly59KFR9WmaQ8eelSvNLJAWCJ10=,tag:2YTI3l+1z9sO2Gr7Csd4aw==,type:str]
secret_mev_flood_user_key: ENC[AES256_GCM,data:KKnBt1BEnBR/Cl9B7FljzV3kJOW9Gmp7DJ46xc1EkUZmWn1f8F4QLhgsyK34FKBKSCmDMCQoctwirAKTG/Vlsw==,iv:efkOBcrGeGJwT91SR+2wFI/fpnWASQeqjH3MJSIQBAA=,tag:1f+bkUNLh8kMsxO5qNQo+Q==,type:str]
secret_xatu_sentry:
    server_address: ENC[AES256_GCM,data:XzLdQ+6JRMe77fQJUJC8pGsVCKB6L4JuQfyTBb84hW9UXrHJ3umII0yQeg==,iv:ITMxKGxTVHDVPYhphwfRtt++DSMrwP5jOPD+/3q8Oig=,tag:cUjDFe+1uFv+tPAPYVnSZQ==,type:str]
    user: ENC[AES256_GCM,data:H/ee8GvkSYtyTzY=,iv:Jjhtt5V0LXcNdS5PjBmYMDLJndPZUd4HPn2pSw4BM34=,tag:vo08KX4A2ic4IqpcBRHRZg==,type:str]
    password: ENC[AES256_GCM,data:6bR/AjXadfHRZyBGlFcgiBnUQMc2xTjFcpgFZg6vxw==,iv:r6FsNBMe6nPCoQ7NuUzSljgKgdvp540kkOD+ApPSmdM=,tag:Df0RYt75FlB2NFakqViJ2g==,type:str]
    event_ingester_auth: ENC[AES256_GCM,data:xD1uqYrRdB+TU7Fqbs+fENWiInVD1HOdVjxppQHhh7jRl+dU9HlJpD60nswd611EyHbWheTnlY1lRMO6Damz0ut9,iv:bKNxaPz+Xj5bIidQlaJrQXaDtT/I0lfBBY3zFfvMCAg=,tag:G1qOLehH6Wm9aI6a2ShqCQ==,type:str]
    coordinator_secret: ENC[AES256_GCM,data:f4y7Ck0Z2zpOo8bHuS/w7Bhk6/6+DIvFXctMhjaMBYWLiwEY,iv:gQG7HBaDQPz0huJH2fq4y8HOGN3JwceJET/spgL5GXk=,tag:2guBo0MRKOMKOhpyjYL0VA==,type:str]
secret_cert_encryption_psk: ENC[AES256_GCM,data:1vRbRAbpo1FKplr8zZZV3UeCLmq6Kx1UJLOqGFYH,iv:iPHM9jsyq9sODiNsuvigQoeRNaQHtgKR55iB0YrGoa8=,tag:gsWdkvxGtAOInEWLOhuH+A==,type:str]
tx_fuzz_blobs_privkey: ENC[AES256_GCM,data:lYDYBAfPdtgovoGtmz7c4lUfiqxr2N0Sp1dkMWn115+TJYBzfpsMdfBl88PfAibFfHwhMhKwpvKTyHSeUzX2xw==,iv:qTk22/lpJyWFycayBupQp0sBaw2E2oq7peWypQh+0Ic=,tag:JhQPq8s3ueLEfL2FJGH+wA==,type:str]
tx_fuzz_txs_privkey: ENC[AES256_GCM,data:5oacWB7naaDLkIihcBK8E2AKPk9OWLz0AJ7ZLKmpTQkstF/idYkjm6GzmaX0LVGxND0DlUO/fcydtY+UFVQoyw==,iv:gHO+ttqzJCbRBCUvmlsTVNQK6vpnGXamIag63HS/fas=,tag:Ub7xqXrx9tYU2ytk/XtJCQ==,type:str]
goomy_private_key: ENC[AES256_GCM,data:cpKpCZPZOZ/oA4zSFJaIutD/H5SUOHLBS/qyKL+5ZOMOvaDVmI3zY3GiQl149LB3tya6Rg2rEQSABxR1fz8c5w==,iv:Ibm4sLvU+tNk7EqaSPs/2CRLU1yLlNDgSWjR+uNPrvQ=,tag:sOvyhcNsNv2Zj/7waeZBBA==,type:str]
nethermind_seq_api_key: ENC[AES256_GCM,data:C6dHJX02l+m0zVYH691GUyKZgRs=,iv:tNCA6W6hJm1PybTE2piAhfUjDKCqQWeN2FQfgiayJC0=,tag:VZiwt+DgR+nfWXdzZjGnxw==,type:str]
nethermind_seq_server: ENC[AES256_GCM,data:wEIM2pUqK+I3rf42maFTr05r8cOJWjnpPQ==,iv:2Iu5nQAjRmxqkOF2Pueup+Kiwd34sfTxWY8aFv0pea0=,tag:VrfL6pUITsKJPgSue/XXJw==,type:str]
nethermind_push_gateway: ENC[AES256_GCM,data:ScReyCHKHx2/8Yo3epSAsb3MykmlIrGkUegaV5+21aboPCgU+VbUOBfvqaTWpcQN3OjXH+euQj1bHL1etGk1qvjzm2sp/P9oqbHRU827nbejkk5SKEeC4q79U7QyQTbUJ1Z9paX1sYZysMDUf2LUb9r/wHhB7bknQYKnHBAg0Li7qw5T5o1yatJoDqfahe4R1Q==,iv:WuQDvBvS2zjEB805HYkq5TQ/H8baF23vyMP9JbdqCao=,tag:jTOnfh2+ZmWIXQBzIpIVCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-20T10:29:30Z"
    mac: ENC[AES256_GCM,data:th1mIooQhIDKsmszJ6d580lBEq/I1uOF1W2V34j0SKHZd1eeMlQGi4NjwCQYPihJ6EOH85ZQb3fIInyOu9/OksPYws2cRqrjU6kKlWD3fafbfee9+wHdcKSipUsOKG895P2WQBvwdNdyI80qHvajopAl7YdTEUHDIvU+8i8bCoM=,iv:rbRKAoX5Q2DCl9byUZpCwDPBb0p2EVZKlhYYE1/uwS0=,tag:ffOeYoxpfDiPbSC68wSiRQ==,type:str]
    pgp:
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pAQ//bdIlIvLrgiEKNc/Z+iWyi1x/DvqnPO0Z2uRDkphoYGUe
            5mDAgLkWWAyYKZP6XN+jNY3h8MON9lBRnheR/cKW0+SGxweX5xVSSxdqZn3Pb3DB
            qcDH6wMXT1mCP0kvDAc9HSYFex4QVfQj6x3fBHyx3FUT/5drwQjms8tiuVBuvSkp
            fJWBQAZgGliG9IXzS9cFEO55/mcvFk+QDvAE5fcsLodloaO8AkpPdfZaVxjS8yWc
            X9NTh7OK8ZiIJftcfPfSUD018TDhJMJLy80XG30pFA7mq1JYJw06AiYFi9zZuujj
            dOknWJaVd1fTI/RgWQj2itX1oF1gZGOO/m6/w6rba7vYK4wpWkitA8Zy8+/mc/tJ
            fsMnejZNHUoRXJ9OmyyH2VNlwxG3OJNqBqAZgBNarvU8DegQCk3Djrca9x/Yppb/
            KEu3vYuq8GoXe3ROmUQJX9E+ReEcWxZFvomt/mXjjofBZxWuPcxgysKeE8rbbbIt
            wktcCg1wH+SeCjym9eDQUKHIVHDQS/PNHVH7wCR8Y3OsVjJd1N02mb+qWxAFTAyw
            p/PEDeF0DnXgnC8kEIE0izK2V6KVWqAOaz5OS/QdFsiVBjkfysjdkEdVRMjvC7zT
            M06dxoj2njkY/OBpovH2mYnwIdhdaUu20B6BGDtSd40zbrvT/eBZF8BWty6yRebS
            XAG+UcjHp1OERkpKHMt15Qfhq6ASe2cBnEODkXh3r3cchvW382WDw4rSwn+Um9Ml
            qLPf2r+Os5z6/GCf6Sr0+A0wl8CJ0fDghpgXUlHM5FBOdGmo2C3WRFk+X4ZT
            =CceJ
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGARAAzds/G3Hazhd/HuZj9Um+qbTBW3fCLYRcTIY5XSq1KM2A
            FXptMH2Pnlhl60DgA7hAb4aLrsoWaVkR93LNXj5DnYPbw7ZIQquoL5u+5gEi81dU
            etPhnECaeofpFY5hzvEcRUYx22LphLxlE8f+yA3Mf9xLT/ax5Ie9N39Dgu6UXAVm
            hBhvaDpC/lp7/GjBi+iBOhlTSiP6J3TKaPW4QKnWqqdsySDxJ7eof+bELTr0rbhe
            OGhj04AIuXqy41VZ/f6wzKiotKojiGCs+U9ZgT1n+EExH0RdwjEBL+FazHHozhBv
            DMcgVA68z9BUoAlk6y/20drZdvo5ufsXyAtaJ/gv280QVvJx3nt0tfvd8nqZ0yv/
            pgF4EYWovtlGVIcjHTEOYVylr9GhXLobfU8d3jw9Cd5tDoeN6bxA3C8KlptXyxjU
            eqVMbiLvI+Lr2xTs6Vz5Y1orZNxCtl/3p22SG4AlPNpg9gamjLTy8s4l+z9i4nTN
            0hGWF/BLbFO+fIo0iUDzerKlTVK4AMBAjyIb71H/JMcix/uCQnC+4KYqHK+qgK4n
            c0nZvyIKvIcSWCpgwA2US2b2BgglT8/wzUrIKHl6XnqGcnGRkU6xlXQwgqWcRHzB
            gu3Iv34YgFiUaGbtQ7yAaEFg0C+5MVhDyCgqJ0b/gFqJcBRmGapN4//VJQeG6SDS
            UQENn2J3svMztRkIkNByMCr/AISI1Wp/I6PCnZaf+ZcfCd8d+QfKb1D/EkpYQtky
            MMHu8dASp6N6uIEL09haqezxLKgzSXaWiEHxOX+BhsiUCw==
            =Y6Lz
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyAQ//R1RZUUkF7442xTKAbtQ4CWNRG8vvR425vuixzta2d0j7
            Xlro9h0H0rbwFBbAD7ZmGs7GBPV4ti/A4r04FGzpZXbqOvf6oXP8bNIAZNsrQ4lf
            2P9o5RkF/u6QYsoFRSoYGEZfODoymYt6kRYmz3iomTG1xDqj1KjkFSwRN8C0sRyH
            cnr9YoRlcPxfRJi9vzkDvg2hJ5FWw0+yB57Qt1vUjSwauZYVGyRYcjdnUTF8vTnB
            fajtdDjysWQwVb8LfW9S6owgf4zBcv/jyYQdQseZEHLkODJKyf6dPceS8xwA87vv
            ljcLF+pzX0YNM83ZtbqGnCl7vWn2KwMS6kcOBOxcUbCPnPHV5W/YJN187AXopy/t
            8U9cgzdlBUZJ9HcxrrUbW0cLDZThywxCP3uSRnKwkYpzytUHQg5jbzlQkYiNwP24
            6Kcm4iFILyRfzEeFeRq5BleucQOPjJl+xFc1mBr5xsno5EN7A6+ou+mh0pyUfuBi
            eLp4uQPWRGCU4XDU0XXX4TkbejNDWNzXh7C2m3rtVwnstKcgA0vHKODcAnAlfN3I
            tkWSeBBQjye/0n+Q1qafavjo1esbU/2OlAEGtJjnkN2cPi/B21TWe1w0PfdKN/vn
            eJtE2HZPFQcob88w8ayE/kDx55jG+7s4gBkK+C0BzMAZ98PkpHJQ44AY4LrenBzS
            UQHcDf6LcFyfdU26+eTKvgUHP4DCv50S2vewPP9IWGlaUCfE5ZlGviIF/k0tbnxt
            ik95wdMncgGtN51H69TnRWQcPgsv0VaYr43br4g1Z5EKLw==
            =6xMz
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JARAAkzfe6tmfGaUDARciy4Se0p0aNjAxPg1wBznObY2Pb+TF
            xlVUrmYd9jbOtLj3vijHPXIQ0mYXWh45GN85JwzdBB1kTw7HDAJ3ep454xXSe3wU
            ZI5eRNqHFMUIVlEyY4pOigyDfdWqsw4ZW2FAW2cwC5u+4nAJJ4mD2DTWOlfLBqyj
            Be/gkckU+UczsGyt1rQtM0UHVhBcjiFhNMAmBHQDXLaWIIIVr4GkvLu3BylRMAV5
            MRB4Wo3iWgzNA9M1oI7jnSay4clpHItFSJzJsLnuP4MuPzwJg4e+saSL6OyZboSn
            CxwpnBw3r7Sgw7d+Vp/xttMmmg+F2DloGehHRboPe2+oIb4GhdKUFUsoVMEi5vIO
            zl1nCOj3rqqrYt0JDjbX/fbLu6eJ92R/MQVW8cx2Blj+7xD7a49KrKDQJNg8GVvC
            tDT+YFdtdx0CLqoqu7AMJZt7T+4A9rG8TH7X/iwqTr2Knhk+bot3nr6fXAOYxOgh
            9uSgWM31SJHhB5GLCJfyDYHQ6bgTYYd+yY0DEyBdw71bhkU1GaE5CxKf0i1idO7p
            yHVZL6hrPLnZQqeA2N/0F+DCYEJ0O4Vv3LxJIIBifL1xnR5fGlINYvRm9oxIeAnu
            cjb2jdd7qVZ4k6ww9HsYnfF0diwHZl1VvuIt3o4V0XRGZ/WkwTyorVzVgO4aV8rS
            UQExWUnFMrSqSHOZIx7L+aR2WRmmTxuxta8RSH6wKs2aoqa2o7J7nE4qE42oPMp6
            Ja5WZJO7xMTOVc7hdKslNwGcck4SKNXZRDbVAkbCUBy9ZQ==
            =IM05
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQf9G963SpBjSsdVEBrzr3tR83sL7cFeqFcpVvl06duTCbrp
            Fv20LWfd+k0xfsxpgWcwfEieviqkoLJZLlRwn8xWIJc1JWGCft3LCdu5MYyKa+cM
            7HzvFpHxJiKhYvJOYmAlbo+r92hFIl1dSlqIX1lHL3Obz67AFp4J/e7ET7ZtXlZ3
            qYCvtogrhDYGmKfI7qK57Zvmw9k0gmo6sefHC1hHS60JzXgJTlcTdZHB6IM9Bu4e
            HmsXcqKgi+kQTILgex7Yo8gdSTC3GfberoBhmDJpZeEM0WWsxl2419PtDQxSkvmh
            unYlG76U+hQ6+w9xO07BG5DacQ4FJJwkBVwgaz3hJNJcAf1SayugSQLXoLTohL4o
            u14yogL09qTOUDR5A6+MpW1uqQu9pckWFp/LaOEVqKv6LnxmmYXTE4rEIvZQsl+d
            FVAKm86kP4CMwAv/fx4KOpZbciG80yUTY51+eNY=
            =OpkE
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ//TmMK92ylfQYGIAKUR73JLLS76b7WTPb0gr0SHmJPF5qC
            VNaedtTBoR0urVMxxZkxIpSKCg+2gmEv2qjzuHuwIwMGFbZv6VVKlEoBmOZoLR8t
            IGyKPfnQhzaT6GanBEA6jZdRTFjXixa5DpX8xxWa+NwFT0kBiMnMfa+/vUKodSuF
            +GBqdRLH+h8vHvfR/1g8fX3monna1AZ2Ezwk2myUgGyiotS7agoa7Z/ROvBOx0Rs
            17PDNVRf2bLZLKilJCOF3X3ehfAQBs9MiaBx3c0Flcus4hiJgfZDMbrDyepbFkEx
            4feTSxPupDMKuecEzEhiQb3lraeQtegNOZG38OJpB3O+/IiMEC9isPW+wO9acUmt
            /73SkiDq+M5loXyOmma70G3XqICy0V4arK/bSevqxA+GwHbQpAcS6VDH8eMe/0PN
            Ze5Ovf8mzA6apu0zIoZUKTHjPxookUgkq4JEX9wK6oobXzhDQxv+Rhm3iemC4qUq
            ENgaxCF+iOMISGb1tTfyA3JXLFHyWAj6V3XrsKEseaelp/dlGUZXrPf38Kj+R74a
            0+rGOn5BNK48DOwAPdWfwGThEBtVIsyN/7NyHUfsQ3FrpcpRBLMDikcIT0f2mk9L
            RrZqx5XxLPOVlQpeQ/4XwCquWyYicXQx6a9tThYWwx9hlARVfJkwDHtFndbUAmvS
            XAFMK6m0z3WQOp+WK5Gagl/sgDw0wyGixefwi6evekbbegBpG80l/jym8E6w86Jx
            30JdCnsqyKIHRwt7CChG3kkKrDq3iuTXi2rtvLVRWb+b7Lh6CMkQe4Dq3w4V
            =l/qn
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtARAAiJ/p5TeTdYK8x/acTcAA2Jr+B03KGgPHkHqsDDjRADvs
            UJSXbDTpY3HSGQjr2znxzIpmlrSYExPRbmigLLhVQYsR4mGu2mVYwFMS6DpHOQcn
            xtnnCkhPinIuTgPyDHV0AsxLhAWpBwZd/WcDNj0oG3J1akQJK8OJiWGYLoEj0218
            Dc7MNghFpp31D3rlGUjTJTLfdm6XrjtUlf56+E8vLDnmB4br9Xe0h/cahxpxHc14
            4oHyOaTPMC07//osDAjkGfoe18GQL4dxnuQtOutpfJvqkDurrIG3TpyxN6ydkKLc
            at3K4SKvEFAOmAzgTNgFyLPeEzXsFofQFZTkHmQPSVF+jy37ichP2VQtkqfVD8Lh
            0CKg4ngj8/0qVmvvtpZaclCGKS8s7lmfZhDqyX6Z/644A6nd1Mdsad+CiwnLfgle
            +Djt18wS+1dIGLCzVqivyOzkyuPNHjhxfI4kMQ4xXrm9ZqtI57yRzH5veO8LpPp0
            keSpGBwcvpX00grRXehAZCCrTW5MZ+5mdN+laVHpSU4MWL0yhutyNrgXQBfn0mXM
            QCsXchwRlf9b7u0agkTodFckj3ANFsY5ucjRIeBGm0mFsoDd75N3vLyiGcx5N1iq
            il8RwvRdp3/uTntfYqYCYHiLop/+vbZYPBSmbt1NuOYgMCEcEMTCSx87CKrx1nbS
            XAHAvqZpm56nyZfm5y/wzQXNCid84brPzQZc9z81PiNY5y6/PnZbsDfK5+CevM94
            bVlIeNG7iTatnlaZSZBBv43EFUYjiutmDgR2KiIuXrZmiUic28+A18DOBU0V
            =CgHr
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdA1ijnliic5ISVYNwOHeqzTZDMtFO0EOthuPPTzxHcZwAw
            OxKYQXcc5s48ztgCpp3EiJDWK1djOj8gPu//023gvQt/9VArSbvREvPasEbMkDMO
            1GYBCQIQC+l1VSlDBplXLj68/SiUORzsaO3lx/6PE6/l8nk1n5tiLvHJxLoxspTO
            Xg2niEaBU6zael0IBeupt6jcFcVnhJCcqpuRL5LgPj0EgoAcgp1DORHzw7PokVoJ
            3Edy96T66wU=
            =6w5m
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.8.1
