# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/spamoor.yaml.j2

spamoor:
  fullnameOverride: spamoor
  image:
    repository: ethpandaops/spamoor
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: spamoor.fusaka-msf-1.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  customArgs:
    - --fulu-activation=1764164520

  persistence:
    enabled: true

  privateKey: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.spamoor_private_key}>"
  rpcEndpoints:
  # Rpc
  - "http://geth-prysm-001:8545"
  - "group(bootnode-1)name(bootnode-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-bootnode-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(grandine,geth,super,1,grandine-geth-super-1)name(grandine-geth-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-grandine-geth-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(lighthouse,geth,super,1,lighthouse-geth-super-1)name(lighthouse-geth-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-lighthouse-geth-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(lighthouse,nethermind,super,1,lighthouse-nethermind-super-1)name(lighthouse-nethermind-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-lighthouse-nethermind-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(lighthouse,reth,super,1,lighthouse-reth-super-1)name(lighthouse-reth-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-lighthouse-reth-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(lodestar,besu,super,1,lodestar-besu-super-1)name(lodestar-besu-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-lodestar-besu-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(lodestar,reth,super,1,lodestar-reth-super-1)name(lodestar-reth-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-lodestar-reth-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(nimbus,erigon,super,1,nimbus-erigon-super-1)name(nimbus-erigon-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-nimbus-erigon-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(nimbus,reth,super,1,nimbus-reth-super-1)name(nimbus-reth-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-nimbus-reth-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(prysm,besu,super,1,prysm-besu-super-1)name(prysm-besu-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-prysm-besu-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(prysm,nethermind,super,1,prysm-nethermind-super-1)name(prysm-nethermind-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-prysm-nethermind-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(teku,besu,super,1,teku-besu-super-1)name(teku-besu-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-teku-besu-super-1.srv.fusaka-msf-1.ethpandaops.io"
  - "group(teku,erigon,super,1,teku-erigon-super-1)name(teku-erigon-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.fusaka-devnets.node_ingress.combined}>@rpc-teku-erigon-super-1.srv.fusaka-msf-1.ethpandaops.io"
