localhost

[all:vars]
ethereum_network_name=fusaka-sepsf-0

[bootnode]
bootnode-1 ansible_host=192.241.152.115 ipv6=2604:a880:400:d1:0:2:fa53:1 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True 

[grandine_geth_super]
grandine-geth-super-1 ansible_host=68.183.129.166 ipv6=2604:a880:400:d1:0:2:fa53:3001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=5000 validator_end=6000

[lighthouse_geth_super]
lighthouse-geth-super-1 ansible_host=167.99.5.69 ipv6=2604:a880:400:d1:0:2:fa53:5001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=1000

[lodestar_reth_super]
lodestar-reth-super-1 ansible_host=147.182.166.52 ipv6=2604:a880:400:d1:0:2:fa53:4001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=4000 validator_end=5000

[nimbus_erigon_super]
nimbus-erigon-super-1 ansible_host=137.184.55.68 ipv6=2604:a880:400:d1:0:2:fa53:1001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=3000 validator_end=4000

[prysm_nethermind_super]
prysm-nethermind-super-1 ansible_host=137.184.17.198 ipv6=2604:a880:400:d1:0:2:fa53:2001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=2000

[teku_besu_super]
teku-besu-super-1 ansible_host=174.138.33.217 ipv6=2604:a880:400:d1:0:2:fa52:f001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=2000 validator_end=3000


# Consensus client groups

[lighthouse:children]
lighthouse_geth_super
[lodestar:children]
lodestar_reth_super
[nimbus:children]
nimbus_erigon_super
[teku:children]
teku_besu_super
[prysm:children]
prysm_nethermind_super
[grandine:children]
grandine_geth_super

# Execution client groups

[besu:children]
teku_besu_super
[ethereumjs:children]
[geth:children]
grandine_geth_super
lighthouse_geth_super
[nethermind:children]
prysm_nethermind_super
[erigon:children]
nimbus_erigon_super
[reth:children]
lodestar_reth_super
[nimbusel:children]

# Global groups

[consensus_node:children]
grandine
lighthouse
lodestar
nimbus
prysm
teku

[execution_node:children]
besu
erigon
geth
nethermind
reth

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
