# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-el.yaml.j2
# Execution layer endpoints

- url: https://rpc-bootnode-1.srv.fusaka-holsf-1.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-bootnode-1.srv.fusaka-holsf-1.ethpandaops.io:8961
- url: https://rpc-grandine-geth-super-1.srv.fusaka-holsf-1.ethpandaops.io
  name: grandine-geth-super-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-grandine-geth-super-1.srv.fusaka-holsf-1.ethpandaops.io:8961
- url: https://rpc-lighthouse-geth-super-1.srv.fusaka-holsf-1.ethpandaops.io
  name: lighthouse-geth-super-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-geth-super-1.srv.fusaka-holsf-1.ethpandaops.io:8961
- url: https://rpc-lodestar-reth-super-1.srv.fusaka-holsf-1.ethpandaops.io
  name: lodestar-reth-super-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lodestar-reth-super-1.srv.fusaka-holsf-1.ethpandaops.io:8961
- url: https://rpc-nimbus-erigon-super-1.srv.fusaka-holsf-1.ethpandaops.io
  name: nimbus-erigon-super-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-nimbus-erigon-super-1.srv.fusaka-holsf-1.ethpandaops.io:8961
- url: https://rpc-prysm-nethermind-super-1.srv.fusaka-holsf-1.ethpandaops.io
  name: prysm-nethermind-super-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-prysm-nethermind-super-1.srv.fusaka-holsf-1.ethpandaops.io:8961
- url: https://rpc-teku-besu-super-1.srv.fusaka-holsf-1.ethpandaops.io
  name: teku-besu-super-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-teku-besu-super-1.srv.fusaka-holsf-1.ethpandaops.io:8961
