cl_bootnode_privkey: ENC[AES256_GCM,data:ywhGk8vFMF6ishOKGWMfSn0IxJttDiSBqaHgserxIamQvRMzJPcmMvAStVfMZB7XBHGyiWLy9vvDFhhQzBiocg==,iv:iEHtpLwDBPbJ3Ny/ZZLf+jX2nWunP21VhgU5D6fiSyQ=,tag:d2jUPi/+szwu4fkG1UuYKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T05:18:36Z"
    mac: ENC[AES256_GCM,data:OvHF2KM4DeBqRrBC2bhcpCrUbW2mwIvt+6+nwXld/qoDhgTxT8DBXGAfFY9wE172uElnV6O2bHGfgwCVX121Jg6d1rYzvcXrXuLaaTqLCTjy3xAkE0GrjJpXDAzhghsY95NU+n3u5Rz+49SffK/sR/dqRyNsASsW64eTzdMvXng=,iv:5di/nwLQieMrIxn6IEOP1UcJjick+X1l0kLka2e/72w=,tag:7jfPRLfWT2WiwllOfvxtEA==,type:str]
    pgp:
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pAQ//RU7r9QbJGCdk393uA87oJLQnRmtJI74xbD9kzmmVF7nO
            OSL9J+7HkxMOe4ZYO7atcGlIfPa6RERmB4XG+nyhkIB0KSuVerf2i8jA8XhDPgbJ
            G+7FdHRWFoFTQxG1UM/hnpN7ygffWned9muBF2j6CWe4a/tS1hOa3t+5kW0xlE3y
            8aDxt/811rJRW0ZINiJoJWujYDEaeL5w59gv6LNXt4Hbg4vRrOH9myXHMaVrW7Iz
            Ho/yU0s2ebMcCLJy2kKwYyTBdm6nZj88v0a5wQkknrwkTl4SwZgzP1IAM27+76IM
            pGAePvucEBBhnKk4nN4PNzql6IBQexuNayUmKvOkOzGVVDRJdmvwRhKC5kp8yeTU
            vGXojeRDcSSydAmcZz/9/xBtH0pKIJbnbp20e/JIJaiwuNuFD//4I2wET9U/U6rL
            KqjzK4e9AorNXnrc50amfS7WvUNh2LIrt+91laQvTMDldRNt+6mz+n1B3B8Am4bX
            TlL/RUphQymr5Gku50L/SDgMgDqOD0EVUqEX7vcOqE/ZkKQhZb300rS3ZlnV28pG
            3jwmUsQ+gYuMpqFJFaqvMOm1+KjDMHIV1X/+rmC43q5H/j6JiNH6QAmlqdefcBYe
            dIV8AxXvgQPKq3qYiWxOripF3WTiLhorNgCJEGdH86QTcW1Mo3B0QqeD7n1of3vS
            UQG9x4EjRsAf9jT5UnmML9iaeeQdfX7vpwtHekEsLWB1Ja21dU6Qs+5Y2H5YvhKB
            14HBUbmmCdZ2rya1OJD45MBWbaw6HEF6t/l4jnt1EgVZDg==
            =Eh/J
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGAQ/+JG9w3rAr3xM27TMRvFA+sstK36nWY6wlXTc5sYN70qRq
            VJtGU2Cj7AJ4FPzKZoG/l5re0n7IecyuaFzDtoA62zPs/Mr6t4Y3pOLOmZ65fUx2
            CQZiB11PlI9OvDSPeKRv20bgCyfDcpvcNe1zWUmamUcTVqgugC1OZOZ+ZI3b9Eq6
            cT+gqsO1+KwJ7xvyicaDHOzgIay6VOFp5Slz4oFTxCnX30h2V6ZFJkwucdZ87oIz
            /OhMgwt2zE94j5uT0OuwSL2u5H49YhO6NNlObm6YPUBNDeF6nBzVvKMirnp4WZgU
            LZCv6Rgzppj1AXjPOBkfx/w3YsioVBlF1r5XILDYuxGu7deL6n3V7qz7FXzDSRlN
            auiP5ybXTDXbozcTveiI5dVFF8qdpAMaZjxmzlHa0uwiHYZ/WND4yq3ZVC3oLh7F
            XDBBP1L1CpELk3rE4iqaWS0NfgHuTEWB08Agn3WjNVSRd0LXG/7uHQvJG/k5LgAE
            xNdnL+M+AanNALI1JzmswS7dLaYF2zJEhZEbxngTpxM7Sywf+fGeOML9BhtfFWLv
            VO+0DUlPmGKzU2+brkGjrZYKiCwVu6RPUlHFSwC3dn26AA/hMAdB5Zc0bLhdciM6
            McKmgzjDIsXEa9emgugPpzJYwIx7bOlIYiXu0BbBHOnvkcJ7a70QIOYwbjRBYGfS
            UQEjQ3oqFL1I+UrETLNRitTOAlXTbSB9SIMlBBdU/78mvvzmi/3APnFW10ShmOkj
            Zj58Jv1b6WI5r8J7NVyVTtl4CifWFrN0GAeaQYdHkGuuZg==
            =z4Xp
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyAQ/+PsFST6P2FARGppeidoRRtjS/QqBTQnBkqX0aAqRPCz1A
            J35hqgxmKdNRMNclA70uWtmGwc7L8jypxdRSXADC4t4J5dvRFFrKVoR6qpcvBlcH
            PKUquFt2Bug2hF1m9Z4EW8OGBoEmZKA2xMmPEsRpZXZDNC7tiim339sWFDoyIgPQ
            Z1pCAgzw/kArBSM79nsc5xGfp/+ndB9cnAaBEKia52Zwrl4nON1uyGwljZ+X+52f
            JAspVWUbHIYSI08wgRWAJ/S3Y2/xI6pTQjIqY/B2Dy1+C3ZY+5kujTfDydFQprGA
            puRVxUnCa8vsrRg80a5A7Ciq6oqWQlIEIZtSOPe4kdlTsqc261YlR7ggOQwV7Rdg
            sxuv6kc2Nd5iRW5ObxDBdXblYlWOvkc721YPGena6wn/FaPEpch9lzFvVxmqjriG
            s4QHw3x5bBOM+gVQmLj0Fvl0t3NEAiXcMWHJB+XyezUChqKRzKOLkHCsa9Q0/CyS
            8RaLu6ljkOo6k/VR9Eoz7N19sivKVWqPYHwJx+KGv47/s+05g5h6Go1h0+KbjmWM
            Lyjg0LJR+bxoGfE0/kYKqVbqI3C4EpxCk6aQlupXBvnDykaDOHyuIY4B9qjUqqD7
            cvIkwak8bU9cL/nu5Aho7e0SJmSxnU0j59N1jOJ9TOGSDFB950ag/BDwteSR8k7S
            UQFU7kwakcHFCHlT8W5CdaM2IVAecwwZKDUnrAPa/lgjwMPlHjvWfN1QzDawNcNo
            ETC5Ylj9y3uup0kpIRFes2fttQz30IamYF68CsIMz8ZlLQ==
            =C/UK
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JAQ//aMz/WnKpQtolHgnRPhLu565nwK9FV72BpFcEnS+JnUOD
            Z+jtnfzhxPi2oXwbb1nbLwSNgetJNluMPEYSh1/UCvipi99Guv0uH/of9dSeqy+p
            CVGpfxNsRC/83aTKX765EKvgDO+twMcobi92EVbRLb6hjUm3Dbbsga5ntKqL/AsP
            aoks/UOLLFh7ixT6HpLwZsTGzAAcc6wZujvEZTyEktxGKwraciHpbx7AOF3pJXnd
            vbxrzq9FuDT7lGsc5MuycfLugWinjKWxR8X66UpdmxC1ZZKfReqsgRlz5kaBpd0n
            Z8ZA+/FrVZPsAC/fPbWlcOHDdPzJMGNy0igkzpbBLgI+ghcmUoI8a4HG9lPb4Ku3
            uRor9hBStwO+4pklJ0TCaV87XkyM8e29T6Mk3qJA7NMUE4vAPJb75PgYY7D/bETb
            zfDTWQOjYIAAOwUnSP4r6OWL1y2EeUgmhHzAnifZKuAhD8sa8JVJLCL6xWcCd0Vg
            04KMBTFgcNT7/gxqY3EAWnqMimALAQW4yfMqC4218hbS/cNDfZNkHpDdZRaHO7mV
            Fr4H8p9RYyIeqwrpzS5/2OqzLPW+Rhg5j3AC3rek4vKsilCih6NNLwryPca3pkjF
            c7LbGRCBN8KICnqqsLvk1SUlb+XzOXZ9kFxcTVBzB7cqcOQmMSmnYMfsiHzK8aHS
            UQG0PdoKE0gkjLInPs8Cp8ESZ94xvJ1VALQSjKJqNftV2SqsCV+jBwn9xRX5AkyW
            3XI+W32xDn06gCu3zyUdZRe4nI0mQo1SSsk0w7Ba9ZjWCg==
            =qInJ
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQf8CujgxmleJ48nRRP2yfrNVXVhpmG+/TYkJVD7OMBeMvWJ
            QxqaSaukk9+3mFTjma5iPIQl+Q09dqfhlp1CLAxPDx6/gf/dSlX79O01+tHRgNnl
            VP/pmvfTfoxeL7PwopM3rKWL6bpyHZs7N9OFP5EzcMf4VOhO+mxJ+vSd2AC1lFlD
            hmI0L2EyJwpmop+GwY8O2xFclgoE9qJVmYxTLwoIeaiSlbRvUf/btaY5QQZhtqvD
            tkMwtz1/bvrBLzXw61RC6aeVon4D/mG9WWJBvM+LvLVNG88uJDtUtS7p1pVthEek
            HqLA1u69IWxM0cpdiTl+M4pfHkhZi45hdUDbjieDLNJRAUZNqHZl56eL6rM882Sl
            0JZ+xAZlUhKWAVplukKZvUNWfed6RFrSZkLO+KFbHkUhnnOF24QiAde1smv1xwEf
            szCnxasdpgWnjKmskG7cM3BD
            =rIEe
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ/9Fs34BRdycGsmbYFE9gPQJRCY6NRWTSG85cb/OyPai4zm
            b9Ajnqu80918jvMjOKtzvGQdwmD3wdRH+3Is68HglXJMCODjOzNiV6GS3N8dACSh
            3fH33zRl/8yuF5R7f+pseDeHDQnpm0ZxbprNqvaH10xpJ8eHSMBssnJluC0H1zxY
            ztuhSQx7ooJs+BQ80nNo4nRowA1Cbk5ZX7zhZWjBYHrtbyxkT34qZw5yIkGlY6sw
            Z4C2e5wrJARHWLZX+lUcW+Prl0Cu4/yH0AaBv+0et2NYWIEcQPFE9qqReBqjrepK
            An+rkLVFinijBqSu5cbCdNTPyxUgalFzaGCwGx1XbzeXPtwCwF7V/jMgU+UYRen3
            7Wt8n8+l8Xm3qSsFvujVFeJcxEd4K+/PPuoIAaIC7L8P9444eGQsy7tIW/CyUPXg
            u0FjdRLN/AF8mA5zYN8RkyHIwUDgvwsr3B8YWw6hY2qI9aDC+0RsxtP+qBwyMR7h
            xmKCUS05Uhp5pBJtHrt4PbRqp3YvTc3jPtCWp/PvXPa+K4VAdpBVl0nwzdgXIE07
            XrY8nZLSl6QNzlxlDW/cIhjSz1j9SmSlkx8INJ7A5b+rFy1hyAMUWR4+DdEbKhij
            x+GBHL+bW8i4Tb0LfGMZceqIO3MDl/vxj3/yE3r6c9H3wmVDgbi7Iq4zTaOsDPLS
            UQGDHonx+DZlvKv9cyXW2eiLMG/HRpffdBp4bvRfSH8GBQ0lOuDpKW4A3okg1Az6
            WKJHHUh7HIyqzenrFSOdGXabUXijtzvPCipFeu9pvL5uBg==
            =3ttc
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtARAAn3y2i2RWa2tGgWbnFOX7O5/EsPT4IC2/5zJxj2SdzqlL
            5HT8T7/o2CZ8n0Y+WXCT1m3fg/9Ckj9pvWj0xhJv9k5CaoZIngVEPUSmXZleSxjB
            G6MJAIQCTovcD0McGlCxSt+3Ho0B+HyFzOE6JWfLhtBl5ghGVr+WgtJEQ5e4fu6f
            xqDF72JmCyQ6lmOBn4HE2DcNgF1JnxQr5/kyCIMd6nzeJ+HA1vX780gBqG1lBIQ7
            6ANcyqhF2VmgFFPlXyhvG2EGx0nlMT8kGMXJpDO30yhgGBB2iCAUT8VrnFIXe5W9
            p3yD8agnB6AGP8ewB+sYnXazBvlttE3h0rAHWSYwla0vlXhO8J4FuU8N+g2WwE9v
            Dyzko0DBd/bgDTw9Hih1zdb67aichHjlB7Vq7CRU05W/vE3IxkZAnc6y25dk4wTi
            N1/tj1t4J6555HeIBmqEf3np9fyraasJxKiGuFKt4CwXz94imfNyonrBEzNbyVZl
            AwQRTl8iFyoQksWHEB8llhjVyrTGRB5nKl0gkf6ctqCm5VENPAOt1jjAOorurg3W
            0362z1blphDCMKew/jOFrzDKqXg+D551UaV2UC8l8Db8+s8zaeRPvs1T/BxDp07a
            U+8Vq8BI9DobxSmFvMogLGdsMf3nT01CVEjnqIbkk3ZP3mJ9pjwuV2qZSp+veebS
            UQGQyY4ye3Cj7lrkVkS7qOQVCOOwXFjVPJwhJZ2Lf5/fP0ylb3JgCbBn7Latb9dg
            e7mXKcjD5z2vwt9rBnVk61soXWXakxe1i5s34K2tjNHoUw==
            =iWBE
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2025-09-23T11:56:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdAhxKz9Z9DVfCMfgwdDjklUFSYEJkudYbP2BJqGs/5L1Ew
            QetjbHaKzainDIveoQ1eMuErrRP9L2n4+nx8YJ83OOeRKWw4S6IP+hxauYQ7IYDx
            1FsBCQIQfO4p+vv/T9A72SRbZ/WvkFlc3lSsdqsY6tbQEKY5DpJYfGWhPCHr9iw7
            N+L2RhSpy5fA8VEnEGfqomp5RIHeYxx+I4irwTjnyHQrqSE8koPv1E1MXXbX
            =VhRO
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
