localhost

[all:vars]
ethereum_network_name=fusaka-holsf-1

[bootnode]
bootnode-1 ansible_host=204.48.24.60 ipv6=2604:a880:400:d1:0:2:ebc6:2001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True 

[grandine_geth_super]
grandine-geth-super-1 ansible_host=157.245.135.236 ipv6=2604:a880:400:d1:0:2:ebc6:1001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=5000 validator_end=6000

[lighthouse_geth_super]
lighthouse-geth-super-1 ansible_host=157.245.3.76 ipv6=2604:a880:800:14:0:1:cc4a:a000 cloud=digitalocean cloud_region=nyc3 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=1000

[lodestar_reth_super]
lodestar-reth-super-1 ansible_host=170.64.181.189 ipv6=2400:6180:10:200::79f1:a000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=True validator_start=4000 validator_end=5000

[nimbus_erigon_super]
nimbus-erigon-super-1 ansible_host=138.197.32.211 ipv6=2604:a880:800:14:0:1:cc4a:b000 cloud=digitalocean cloud_region=nyc3 ethereum_node_cl_supernode_enabled=True validator_start=3000 validator_end=4000

[prysm_nethermind_super]
prysm-nethermind-super-1 ansible_host=134.199.172.44 ipv6=2400:6180:10:200::79f1:9000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=True validator_start=1000 validator_end=2000

[teku_besu_super]
teku-besu-super-1 ansible_host=143.198.47.245 ipv6=2604:a880:cad:d0:0:1:500:6001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=True validator_start=2000 validator_end=3000


# Consensus client groups

[lighthouse:children]
lighthouse_geth_super
[lodestar:children]
lodestar_reth_super
[nimbus:children]
nimbus_erigon_super
[teku:children]
teku_besu_super
[prysm:children]
prysm_nethermind_super
[grandine:children]
grandine_geth_super

# Execution client groups

[besu:children]
teku_besu_super
[ethereumjs:children]
[geth:children]
grandine_geth_super
lighthouse_geth_super
[nethermind:children]
prysm_nethermind_super
[erigon:children]
nimbus_erigon_super
[reth:children]
lodestar_reth_super
[nimbusel:children]

# Global groups

[consensus_node:children]
grandine
lighthouse
lodestar
nimbus
prysm
teku

[execution_node:children]
besu
erigon
geth
nethermind
reth

[ethereum_node:children]
consensus_node
execution_node

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
