cl_bootnode_privkey: ENC[AES256_GCM,data:ywhGk8vFMF6ishOKGWMfSn0IxJttDiSBqaHgserxIamQvRMzJPcmMvAStVfMZB7XBHGyiWLy9vvDFhhQzBiocg==,iv:iEHtpLwDBPbJ3Ny/ZZLf+jX2nWunP21VhgU5D6fiSyQ=,tag:d2jUPi/+szwu4fkG1UuYKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T05:18:36Z"
    mac: ENC[AES256_GCM,data:OvHF2KM4DeBqRrBC2bhcpCrUbW2mwIvt+6+nwXld/qoDhgTxT8DBXGAfFY9wE172uElnV6O2bHGfgwCVX121Jg6d1rYzvcXrXuLaaTqLCTjy3xAkE0GrjJpXDAzhghsY95NU+n3u5Rz+49SffK/sR/dqRyNsASsW64eTzdMvXng=,iv:5di/nwLQieMrIxn6IEOP1UcJjick+X1l0kLka2e/72w=,tag:7jfPRLfWT2WiwllOfvxtEA==,type:str]
    pgp:
        - created_at: "2025-09-23T11:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA32GcoRiZf6pARAAgxW95YpYiNy9mZo7jN5K8hSfVGk2rSC6tQrXz4hJmgLd
            rBGIXKjzpllcMisOkU0bXmQEef1J6Q+xVlXjwn/s2h1IMTr9Y5xEyoiNTl20XwFh
            dpelNx14zMhQxpakHFzjDaeugN9dhHK/B5bYRuOxLU+fcIdOc3jf3GpbDIiBr1Au
            nP4adENmycLA3MBd/S2XjmHeR0SGtgYugOI45GkooZPsGGxDg1SNbSUMm+Bnw+Gx
            SURJ21bHGgB0ki9FfwPvBxUDvHgFDvNggYJI/qBMMeYhAtggonI/bRAK5NkkDXt0
            79TbOFkjtyBGciuEY7BfDr0BbfqpJVOefUyJDt0bHbSTC+/SpztEk8i1LipNbpKz
            RfIwv64k50x5kbd+gY9TV0Kw4IAsNJobwwGLJchvzvUx6/ViWzSO3yK7LQyK4q/A
            RXdnA73Luas0R3oZOMS317cKZVp1Tkmr8LLbTYrzL8oBs7cEEEaZ5+rr49kLFgOe
            Q0NpdbVU2P3EgzBfmtynbj/KhUxeN1pFTT6sEworiG0F8USuvYBJz/zeueljOGV5
            IW4npM/bODhFAdZJEDOM/IW74i3BrnXnsxuLRERG6fYu+OspLNlMU00Z1/rwQmBN
            QZgOEfYMDV9OeMWLIHTGzVnkqHmXm4T9C9HbcpMkjgm4jjwSmANmkQGBW+U2C17S
            UQEsUiGwb7EIkYIUPbGlly8waKKylnOrVCM7DJgyJZ+99maFey3NChirmyM1Mto/
            wc65M4Lf7fF9rTGOUY9yrcogG4NjxdJ6hqVeuPMDslfVHQ==
            =xdcQ
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2025-09-23T11:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA87Wber4r4dGARAAoAwmSA8S96WVhWpPsRqXqo37NSLhAWWcv+33RsyB9g/B
            RtciaJz68oyW+pb2ikHKv7WnkhNTz/sCwY4kMyalTwqh1e4gqJY6rA5XQ0DLKBzv
            Lf5qlb3K5sGZHWCvcu1fLFlh7t9u7ck4wa3GlQxg0/V78bV3sS+Y8LF9gfQdR+r8
            U2x6rVAtweodUPy5p7paGgWl15jiubiT1b3W83H70RD88vLbEoYyhrlZBGvM5C8M
            4f2U675dsVJCCdb1Ycr2N2j7/aTEUlyXywxhc24Sqo7yAwHyWnZk0k0zbTNcBibW
            7xrhQbzO25bYA82TdgXcyS93FaqWXvNxgZ1OkpE68vb4mUuGoU0yultQuC48APd5
            s1lsTUQIcuDRYURB8gJmSAp005m0H4ko6QUVR1b2FIW+RcfbslyrMK7gG9MEG2fg
            dGwOgfT3AQmCKGGpJjOe2Xhdkts4Rd+c25OZCcoaA9FSsE9id8iCX+0OCKDPhuaT
            r8+2GWZIMJ+9lJaLhBwn85Dq0IeC9+2MJUB9daL3yjsge/qh7MFKomZdGLqui3ON
            ESMDu3zP5W1h28HLP8hgwSPSx7pVQc66cQtpAizeXqu8Qn0iLXWS9cQ2tw3h4v0s
            EVLWMBI/19FYrozc4VSeTDSDbwdYDQglvxkWfDMg9GfFz58PCRJUXAIdxwl76TfS
            UQFWZjTz22/NwbdyEmtGbV54O3bBnu9aHZczVASVWEaSWMvVHVk9/1BqRWVRe9F+
            Fgy43qpxLFvn+AKiDsMUL7lSWB6MoyVMJ3idQOi8oXX24w==
            =XuXX
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2025-09-23T11:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyAQ//fdXPEW9kEe1ocgaFQTP+bHot6a2oTSBWLycGCZBKjmmm
            K5SOD5iGeaLfnjIk9NfAgme4MqYqEbL7ia3AZL5DrHNx7+lgvJxDHDJQdMBPFAnV
            yZS106js9rbDmx3pSs9sSyZvNinlY9rc/JTwidWPvNcrrrR9p/er1MJTGk2YRL8B
            axBHXtxocm/X8pT0AK8t8Xp1FLpTth0YIr/xVYSj+EGYhzLyhu+FUGfTuhxKTfgB
            WEwMKxVV1ROTNw1YEkH2jUgHZbwi9j2VXwVb0UCBpzLQQs4QwDGkDDyNqc3gv3A3
            IwxrWrAf1gxgGC+gfktjG3tYbGwBInpYfcT18AO16njqBprorbp5whDZmD12XpxW
            rkQ8AGW1o36VZsLHpTuLlgzaSqoOLe/iUtgPR/2OVVxEIsCDhPiKb/M8XxMtsGOk
            cTexnr1Mbecvsf6wG9E1HIUlwfcUj02YWSJrO+9kN0LnpOvqju2PzQUmAglnypvX
            TuED33JedhWnPvzt5SHC2KssWl1GyB/rFn/Pg9BMD25wifQrerbbFZJndoVMwirV
            J4YZs5BssrO4V9FD7sm5XcsYWXsl0B79p+vLk7Q1GCM/Ds1o1ZdvcvF1OxE8q7eK
            5NW3ong2/R9tOLvikc2UearfrYGE1AfvcsaD5hdici1ytkUljRaYMNh28FkpdJnS
            UQFLUFLcnzcF+gHCobUDAf3dx/+/PWsEjuCNgnFsIm7PNlqeUEbzSAjBEqfZSC3v
            DMdPpjS4drvpNcFca+yz82vK65VMRD8pUwvakXXaKFG9bw==
            =m7F+
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2025-09-23T11:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw01qfIBwY0JAQ/+KTdhwfw4A3l4LXe1AXja26Dd/LfuAhPrgH/zdBaZPw6I
            1EmGbINT1AW5JHHKyXLYmc8ozxwbWAvcrh96XrlYmVt4/jMkF7mX2m3Iu6NZcecQ
            mmFwXooTMIpEMewhcgpzfF7lW9pz6oY2mrUM8Uy0G+Uxg4JnEyV9OHJmyxWqAknH
            EKHhXWj6dDKhUJccPzxAfJpJt8LihR+tgXI/R008nlthLFZUHbnl9FTMQRHslbyc
            OPxjWk9+GOwkoCwAjF4xfJzuZ/zSidxru7UMq6QqLtAXN3qWWxuFZh9hxO0TlwjZ
            J14jnR3bpM9gw9DkUSLAVqdIwkshVDW28MIt+NdP89SJ4ATV938U5KsgsVhjlS1F
            qiapilrYWQ8rrbkBLc4oJZq60bOVTysVVQZdKS4aOKWn9ZaxJ8AEr8DkhH4b5M06
            nfHN5xxoW0Eaf7Xo3IByfvI2XieYidQ05KF6WB2CnIQ5gYV7VFvxESrdXv3yO0ha
            7zjYcTcdnJmnrUCzDzRDjQeAZhTW4xQsk3Tie+XO4yW27Gt2d878+Oaz+pki7hWe
            v7h8wrDjA6wKVlVNmMSa3PWWEOWoYRXKH4FK9Skg659oumD93PAnlRj9M0+XCLeg
            Nu5XAhxc4j3uP0nPEXOP/7ctABISeLxgZNj4MuW95HEx5R6obi8NHHehZA14WmXS
            UQFWrlzFh5OQ1q9tZtUk0BRSVrbXcZK8OWfT6W0qYMajyEA3NyKVP6g3P39zkBJQ
            I8yvqVg3sTvPZyDKVDYdcxT8LpUjX1jtOmBwyqd+tPxtMA==
            =/Su5
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2025-09-23T11:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQf8DvbbO/4Q0feDX997DjDZWHwHac6kw3DV0d9kUmcQ86Lx
            SKNG3QU/TE2zwwmtML+gH25glzs0lUvIanhMWB5fJymeNyCnRxeuYh/0bzTVjMJu
            jYegWziQZ3uG+q8KzGJzWmdDG4ovvCjYWdf9GPtXlJ/Zq35+wchg6iwf0IG5F/lF
            YvrEi+qKr/5BIGtF8NHRfV0c78TmLtkYV5UeH1vTlPM0n1RJ8G64sv3XVMsKGy1M
            RdlEyetUSHW/LEtYklddF74bnYaPoB5PNBksd0/Xfp96qea8MKHDElktyR5TXTaS
            A60Rz1r7MQdcYwO/F5gXcO0ZXBtyqS/SxsTqzw4zMNJRARDYWdxm7uFizd7pkl5f
            BnJG/3kaMMNdKAmtkxh6T6oNdSXiIfkOdetewvi56mOpCF+F67F2gHY+SeP45deJ
            hjHdouBdbcwiaRii3nAeH8bL
            =rgnk
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2025-09-23T11:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ//WdWmYrv/NUmDKbmlrJmr3EqhjCSWj/Jv9TW2H0YUnztH
            Ke3tH2nzIgXKQuBLDi3aLGa9gVky+jH0B+XOVhJq3R1LxwXmU2PE5sABE246szxa
            Zfyky2vMeTeS50omV3h82Z4EdZoPN2tPILj1REfEtQZJXd5pF1AMsIaW1hFnD3YD
            sfiuB7BtvNQAEKGz9q3mT/PHbYHQlU9gm9gbONJmT+yp/R21S7kcwvVVdwX/VMLv
            rRnPbF6Ig14zoev8J34ML1OGWdnttCIIR/EAI0pxf2qritWKI9LrZHO+A5oEDkKH
            z45GKlE6EtyJVkvE6FAHiGhGsl/X3E41/PdpcR2AmOKcTsZ/96LALtZuaGVoHlne
            PSYyAI9oNLCL5gtkaQDV/vW9RFIqrCQMamf4GMMkFHv/SSKuvTFn3mff1/ouxZv9
            ggI9LXhM1e3Cyw1p4+faxDJEXZpHUOogaajWreltrH3UIyVgDFOzvHlign+yKPLt
            000q77Vdgz54p8x/DGqQWnjcCiEnc+frdd0yc0WWYrVJHi3LejuUNYNYHeV/Vwdh
            h7P7oTBa5nJSLfZOOy6sy221+C4NhFxQkwt7Ixjad3ubBP7R5WTc5wpEtrFbJw3Q
            Mtmgks1tos7dWHtpRghdBACwjxNZYpJWW8szevkslnlK6W1p1lmWGj+xofhIouXS
            UQHS2M51VLQrpGAADVcKApWcHybAmXDWfXB51FCTV2HxpYz6pJFv+GUl6aO6Yw6o
            GHeuHeR03lFthXJFR2splFEtyMr23GGvdqGwa+rqhKlr8A==
            =88Os
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2025-09-23T11:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxYzhHRfYJYtAQ//cdVKE9NVuY3A54FDzbqLphnt1/LxG3QqXGgdP0G2wUMe
            z7bav0LjUzNhtzlF1YdiNsroPYa83/iAXIYsjKqdZpJZGy4RGKH0uRQANIzMlIOq
            j9A/da23WPIhU5BXazltBrtSCcpg9Omio9JTYvarFRQmsjtDhDh9ocyozWeHmd0T
            716j8af0yeVCitkr3wTEMSGKlhTUKZ39AnDZNgjAjzu5M7vu+ZY/jJRJIlTJl/1U
            0vPjh958LT87h/52QmzOW1LaYh2icT8QPjD65b75VNxUe15OIrIpVGeCyVaJXkW+
            AgbVWXQ+0VZsNN0soZclqILuJmzV4KNa1wcutYbkdgMJ0CLGo7M7O4/gIl20PUPM
            voLy9y+AMNjuK4efzanPtktQ8RhEMb1e/jS/nu3eOEQQJHL/Qmdvcs727NJoDeJD
            oIucZojjqiSQHw7RRIdqvDo48EOXGuoMgjlWC3rj2XrWbkDvX9Q8Rl7U4EWvVtjk
            AHV/2VxFtxb7aoLbkgVF0zfMeIzOroz1G3MmJFwYqDLAx2zFFg4zH15Spre5OuMh
            4wv3mA7IOuEo8i/+YK8lqYXIl5pEXw1xYxtexxz5fKIuIZdOk41otnGCt+9emGSk
            y1BqIxP5wElRbO6geaGjk0UueFEPAuO5D08um7IrPdBcJYBpo/nsOSyWYpSHHaPS
            UQEA3+xTNz5JpC/a2Bg4FnLKUccYmK9OryfhpS+XRwCThTfJrXwo9nNwCAtCK4q0
            Kv3XR/WikKBmpLPuA/Zvt2RfpFl3EUJ8y2x2K/nv5cNvPg==
            =fyWM
            -----END PGP MESSAGE-----
          fp: 9BE537027CB7467923E240FF2AED09371C121F91
        - created_at: "2025-09-23T11:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DjS7VXZx9i8YSAQdAKOHQYnAhb7Rula9RjuSsegdoMRHL1E96ZMxRtfH2RRkw
            jUU2b8mP0KivkFwIdPg39dAUfcHDXXCri00AXzu0hVSDZeLw/zWVlS6iv66bAAMP
            1FsBCQIQfXiDYAUt6+fErd/Kft1Frz3VFYl0J92ocvFlpbAcnCP+8Yrwm7qYk6+8
            5Ot3UVZgUeuZClyeqJDKZ5ILXA5XukqjCzfeFvvauRjPBgK7Kl+wNNce9BNK
            =ZokF
            -----END PGP MESSAGE-----
          fp: F93098C3D8ED15D0924A6DDAEB4E93A88660C55B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
