localhost

[all:vars]
ethereum_network_name=fusaka-devnet-3

[mev_relay]
mev-relay-1-arm ansible_host=5.75.142.189 ipv6=2a01:4f8:1c1a:de8b::1 cloud=hetzner cloud_region=nbg1-dc3 ethereum_node_cl_supernode_enabled=True

[lighthouse_reth]
mev-relay-1-arm

# Consensus client groups

[lighthouse:children]
lighthouse_reth
[lodestar:children]
[nimbus:children]
[teku:children]
[prysm:children]
[grandine:children]

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
[nethermind:children]
[erigon:children]
[reth:children]
lighthouse_reth
[nimbusel:children]

# Global groups

[consensus_node:children]
lighthouse
[execution_node:children]
reth
[ethereum_node:children]
consensus_node
execution_node

[mev_boost:children]
consensus_node

[arm]
mev-relay-1-arm
