xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "fusaka-holsf-0-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "fusaka-holsf-0"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://e2617c763cd9d2b6e2d9eb4736ff949e8b57763771d2e5de38322076d923e5f3101204430e8ef7589fa1796233dc6897d15cae5f404878c45d5f41010ea438e7@137.184.106.87:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
