name: Hive -  EEST Common
on:
    schedule:
        - cron: "45 9 * * *" # Daily at 09:45 UTC
    workflow_dispatch:

jobs:
    trigger-generic:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      await github.rest.actions.createWorkflowDispatch({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        workflow_id: 'hive-devnet-2.yaml',
                        ref: 'master',
                        inputs: {
                          simulator: '"ethereum/eest/consume-rlp","ethereum/eest/consume-engine"',
                          concurrency_group: 'daily'
                        }
                      });
